### ISSUE TITLE
Java HTTP library doesn't follow http<>https redirects

### ISSUE THREAD

**Issue by rohieb** [Wilm0r/giggity#77] opened 2018-10-08 10:50 UTC
Giggity 1.3.2 installed from FDroid.

I'm trying to load http://osseu18.sched.com/all.ics by adding it over the `+` button, but when I do this, I only get an error message saying "Load Error: Network I/O problem: java.io.IOException: Download error: no-cache".

A short curl shows that the HTTP URL is only redirect to the HTTPS version:

``` console
$ curl -I http://osseu18.sched.com/all.ics
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://osseu18.sched.com/all.ics
```

(note the `Cache-Control: no-cache` which gets reproduced in the error message).

When I try loading the HTTPS version instead in Giggity, everything works fine, so I guess only the redirection feature is missing, or the `Cache-Control` header is confusing the download logic.

**Comment by Wilm0r** [comment] 2019-10-13 22:07
The bad error message was fixed by https://github.com/Wilm0r/giggity/commit/9b1ad18a5e1fcf62981b94e6d619caf984498d79 , but yes, 302s are still not handled properly.

I do see now that I've enabled the right library flags for them but Java by design doesn't follow https<>http redirects: https://stackoverflow.com/questions/1884230/httpurlconnection-doesnt-follow-redirect-from-http-to-https

The HTTP code is kind of fragile already so I don't feel *too* much like adding this, but I wonder whether I could just make + default to https URLs, given the year we're in. The lack of redirects is not a big issue otherwise since almost everyone opens schedules through the seeded menu.

**Closed** 2019-11-27 22:49 UTC
